name: Issue Management

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Notify about new issue
        run: |
          echo "Se ha creado un nuevo issue:"
          echo "${{ toJson(github.event.issue) }}"
      
      
      - name: Assign user to issue
        run: |
            curl -X POST \
              -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
              -H "Accept: application/vnd.github.v3+json" \
              https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/assignees \
              -d '{
                    "assignees": ["kfjaramillo"]
                  }'
        

      - name: Add labels based on issue
        run: |
            if echo "${{ github.event.issue.title }}" | grep -q "bug"; then
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
                -d '["bug"]'
            fi
        
            if echo "${{ github.event.issue.title }}" | grep -q "feature"; then
              curl -X POST \
                -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
                -H "Accept: application/vnd.github.v3+json" \
                https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.issue.number }}/labels \
                -d '["feature"]'
            fi
        
        