name: Issue Management

on:
  issues:
    types: [opened]

jobs:
  process_issue:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Notify about new issue
        run: echo "Se ha creado un nuevo issue: ${{ github.event.issue.title }}"

      - name: Assign issue
        run: gh issue assign ${{ github.event.issue.number }} --assignee kfjaramillo

      - name: Add labels based on issue
        run: |
          if echo "${{ github.event.issue.title }}" | grep -q "bug"; then
            gh issue label add ${{ github.event.issue.number }} bug
          fi

          if echo "${{ github.event.issue.title }}" | grep -q "feature"; then
            gh issue label add ${{ github.event.issue.number }} feature
          fi
